# Generated by Django 6.0.1 on 2026-01-25 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_console', to='games.console')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_status', to='games.gamestatus')),
            ],
        ),
    ]
