# Generated by Django 6.0.1 on 2026-03-03 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='landingpage_game',
            field=models.BooleanField(default=False, help_text='Add the game to landing page?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='console',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='games.console'),
        ),
        migrations.AlterField(
            model_name='game',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='games/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_statuses', to='games.gamestatus'),
        ),
    ]
