# Generated by Django 6.0.1 on 2026-03-03 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='photo',
        ),
        migrations.AddField(
            model_name='game',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media', to='games.gamestatus'),
        ),
    ]
