# Generated by Django 6.0 on 2026-03-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_game_photo_game_photo_url_alter_game_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='completion_date',
            field=models.DateField(blank=True, help_text='Date when the game was completed', null=True),
        ),
    ]
